name: Setup BoxLang CLI
description: Sets up BoxLang for GitHub Actions

branding:
  icon: terminal
  color: green

inputs:
  with-commandbox:
    description: "Whether to install with CommandBox (default: false)"
    required: false
    default: 'false'
  commandbox_version:
    description: "CommandBox version to install (default: latest)"
    required: false
    default: 'latest'
  commandbox_modules:
    description: "Comma-delimited list of CommandBox packages to install"
    required: false
    default: ""
  forgeboxAPIKey:
    description: "ForgeBox API Key"
    required: false
    default: ''
  modules:
    description: "Space-delimited list of modules to install"
    required: false
    default: ""
  version:
    description: "BoxLang version to install"
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:

    - name: Set up Temurin JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup BoxLang ${{ inputs.version }}
      shell: bash
      id: install-boxlang
      env:
        TERM: xterm-256color
      run: |
        # Download BoxLang shell installer
        echo "Downloading BoxLang installer..."
        if ! curl -fsSL https://downloads.ortussolutions.com/ortussolutions/boxlang-quick-installer/install-boxlang.sh -o install-boxlang.sh; then
          echo "Failed to download BoxLang installer"
          exit 1
        fi

        # Verify the installer script exists
        if [[ ! -f install-boxlang.sh ]]; then
          echo "Installer script not found"
          exit 1
        fi

        # Make the script executable
        chmod +x install-boxlang.sh

        # Call installer with desired version
        echo "Installing BoxLang version: ${{ inputs.version }}"
        if ! sudo -E PATH="$PATH" JAVA_HOME="$JAVA_HOME" ./install-boxlang.sh ${{ inputs.version }} --without-commandbox; then
          echo "BoxLang installation failed"
          echo "Java version:"
          java -version || echo "Java not found"
          echo "JAVA_HOME: ${JAVA_HOME:-not set}"
          exit 1
        fi

        # Verify BoxLang is on the PATH and show version
        echo "Verifying BoxLang installation..."
        if ! boxlang --version; then
          echo "BoxLang installation verification failed"
          exit 1
        fi

        # Export BOXLANG_HOME to environment
        echo "BOXLANG_HOME=$HOME/.boxlang" >> $GITHUB_ENV

        # Capture version and installation path
        BOXLANG_VERSION=$(boxlang --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?' || echo "unknown")
        BOXLANG_PATH=$(which boxlang || echo "unknown")

        # Set outputs
        echo "version=$BOXLANG_VERSION" >> $GITHUB_OUTPUT
        echo "path=$BOXLANG_PATH" >> $GITHUB_OUTPUT

        # Clean up
        rm -f install-boxlang.sh
        echo "BoxLang setup completed successfully"

    - name: Install BoxLang modules
      if: ${{ inputs.modules != '' }}
      shell: bash
      env:
        TERM: xterm-256color
      run: |
        # Source the shell to load PATH and environment variables
        export BOXLANG_INSTALL_HOME=/usr/local/boxlang

        # Check if BOXLANG_INSTALL_HOME is set up and source it if needed
        echo "BoxLang Home: ${BOXLANG_INSTALL_HOME}"

        # Install any BoxLang modules requested
        INSTALL_MODULES="${{ inputs.modules }}"
        echo "Installing modules: $INSTALL_MODULES"
        if ! install-bx-module $INSTALL_MODULES; then
          echo "Module installation failed"
          exit 1
        fi
        echo "Modules installed successfully"

    - name: Install CommandBox
      if: ${{ inputs.with-commandbox == 'true' }}
      shell: bash
      run: |
        # Latest Stable or Specific Version
        if [[ "${{ inputs.commandbox_version }}" == "latest" ]] ; then
          echo "Installing Latest Stable CommandBox"
          curl -SL -o box.zip https://www.ortussolutions.com/parent/download/commandbox/type/bin
        else
          echo "Installing CommandBox v${{ inputs.commandbox_version }}"
          curl -SL -o box.zip https://downloads.ortussolutions.com/ortussolutions/commandbox/${{ inputs.commandbox_version }}/commandbox-bin-${{ inputs.commandbox_version }}.zip
        fi

        # Unzip and Install
        sudo unzip box.zip -d /usr/local/bin/ && rm -v box.zip

        # Make CommandBox executable
        sudo chmod +x /usr/local/bin/box

        # Verify CommandBox installation
        echo "Verifying CommandBox installation..."
        if ! box version; then
          echo "CommandBox installation verification failed"
          exit 1
        fi
        echo "CommandBox setup completed successfully"

    - name: Install CommandBox modules
      if: ${{ inputs.with-commandbox == 'true' && inputs.commandbox_modules != '' }}
      shell: bash
      run: |
        # Install CommandBox packages
        INSTALL_MODULES="${{ inputs.commandbox_modules }}"
        echo "Installing CommandBox modules: $INSTALL_MODULES"
        if ! box install $INSTALL_MODULES; then
          echo "CommandBox module installation failed"
          exit 1
        fi
        echo "CommandBox modules installed successfully"

    - name: Configure ForgeBox API Key
      if: ${{ inputs.with-commandbox == 'true' && inputs.forgeboxAPIKey != '' }}
      shell: bash
      run: |
        # Configure ForgeBox API Key
        echo "Setting up ForgeBox API Key..."
        if ! box config set endpoints.forgebox.APIToken=${{ inputs.forgeboxAPIKey }}; then
          echo "Failed to configure ForgeBox API Key"
          exit 1
        fi
        echo "ForgeBox API Key configured successfully"

outputs:
  boxlang-version:
    description: "The version of BoxLang that was installed"
    value: ${{ steps.install-boxlang.outputs.version }}
  installation-path:
    description: "The path where BoxLang was installed"
    value: ${{ steps.install-boxlang.outputs.path }}
