name: Setup BoxLang CLI
description: Sets up BoxLang for GitHub Actions

branding:
  icon: terminal
  color: green

inputs:
  modules:
    description: "Space-delimited list of modules to install"
    required: false
    default: ""
  version:
    description: "BoxLang version to install"
    required: false
    default: 'latest'
  skip-package-install:
    description: "Skip installation of system packages (curl, zip, unzip, jq, openjdk-21-jre)"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - shell: bash
      id: install
      run: |
        set -euo pipefail  # Exit on error, undefined vars, pipe failures

        # Set TERM to avoid tput errors
        export TERM=${TERM:-xterm}

        # Install required system packages (unless skipped)
        if [[ "${{ inputs.skip-package-install }}" != "true" ]]; then
          echo "Installing required system packages..."
          if command -v apt-get &> /dev/null; then
            # Ubuntu/Debian
            sudo apt-get update
            sudo apt-get install -y curl zip unzip jq openjdk-21-jre
            # Set JAVA_HOME for Ubuntu/Debian
            export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
          elif command -v yum &> /dev/null; then
            # RHEL/CentOS/Amazon Linux
            sudo yum install -y curl zip unzip jq java-21-openjdk
            # Set JAVA_HOME for RHEL/CentOS
            export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
          elif command -v dnf &> /dev/null; then
            # Fedora
            sudo dnf install -y curl zip unzip jq java-21-openjdk
            # Set JAVA_HOME for Fedora
            export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
          elif command -v brew &> /dev/null; then
            # macOS
            brew install curl zip unzip jq openjdk@21
            # Set JAVA_HOME for macOS
            export JAVA_HOME=$(/usr/libexec/java_home -v 21 2>/dev/null || echo "/opt/homebrew/opt/openjdk@21")
          else
            echo "Warning: Could not detect package manager. Assuming packages are already installed."
          fi

          # Verify Java installation
          echo "Verifying Java installation..."
          java -version
          echo "JAVA_HOME: $JAVA_HOME"

        else
          echo "Skipping system package installation as requested"
        fi

        # Download the shell installer with error checking
        echo "Downloading BoxLang installer..."
        if ! curl -fsSL https://downloads.ortussolutions.com/ortussolutions/boxlang/install-boxlang.sh -o install-boxlang.sh; then
          echo "Failed to download BoxLang installer"
          exit 1
        fi

        # Verify the script was downloaded
        if [[ ! -f install-boxlang.sh ]]; then
          echo "Installer script not found"
          exit 1
        fi

        # Make the script executable
        chmod +x install-boxlang.sh

        # Call it with the right version from the input above
        echo "Installing BoxLang version: ${{ inputs.version }}"

        # Ensure JAVA_HOME is set if not already
        if [[ -z "${JAVA_HOME:-}" ]]; then
          if command -v java &> /dev/null; then
            export JAVA_HOME=$(readlink -f $(which java) | sed "s:bin/java::")
            echo "Auto-detected JAVA_HOME: $JAVA_HOME"
          fi
        fi

        # Export environment for the installer
        export JAVA_HOME
        export PATH="$PATH:$JAVA_HOME/bin"

        if ! ./install-boxlang.sh ${{ inputs.version }}; then
          echo "BoxLang installation failed"
          echo "Java version:"
          java -version || echo "Java not found"
          echo "JAVA_HOME: ${JAVA_HOME:-not set}"
          exit 1
        fi

        # Install global dependencies
        INSTALL_MODULES="${{ inputs.modules }}"
        if [[ -n "$INSTALL_MODULES" ]]; then
          echo "Installing modules: $INSTALL_MODULES"
          if ! install-bx-module $INSTALL_MODULES; then
            echo "Module installation failed"
            exit 1
          fi
          echo "Modules installed successfully"
        fi

        # Verify installation and show version
        echo "Verifying BoxLang installation..."
        if ! boxlang --version; then
          echo "BoxLang installation verification failed"
          exit 1
        fi

        # Create the BOXLANG_HOME that points to the user ~/.boxlang directory
        echo "BOXLANG_HOME=$HOME/.boxlang" >> $GITHUB_ENV

        # Capture version and installation path for outputs
        BOXLANG_VERSION=$(boxlang --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?' || echo "unknown")
        BOXLANG_PATH=$(which boxlang || echo "unknown")

        # Set outputs
        echo "version=$BOXLANG_VERSION" >> $GITHUB_OUTPUT
        echo "path=$BOXLANG_PATH" >> $GITHUB_OUTPUT

        # Clean up installer script
        rm -f install-boxlang.sh

        echo "BoxLang setup completed successfully"

outputs:
  boxlang-version:
    description: "The version of BoxLang that was installed"
    value: ${{ steps.install.outputs.version }}
  installation-path:
    description: "The path where BoxLang was installed"
    value: ${{ steps.install.outputs.path }}
